const english = {
	code: "english",
	name: "English",
	// Stats
	screen_name: "Name",
	co2_consumed: "CO2 Consumption",
	location: "Location",
	money: "Money",
	time: "Date",
	real_time: "Playtime",
	distance_traveled: "Distance traveled",
	screen_name_tt: "Current player's name",
	co2_consumed_tt: "CO2 Consumption",
	location_tt: "Current location (airport)",
	money_tt: "Your money",
	time_tt: "Current date",
	real_time_tt: "Playtime",
	distance_traveled_tt: "Total distance traveled",
	flights_tt: "Flight points",
	score: "Score",
	// Floating texts
	not_enough_flight_points: "§<c>red<c>Not enough flight points!§",
	// Characters
	narrator: "Narrator",
	granfather: "Grandfather",
	ronald: "Ronald",
	// Settings
	gameplay: "Gameplay",
	flightSpeed: "Flight speed",
	sound: "Sound",
	musicVolume: "Music volume",
	soundVolume: "Sound effect volume",
	language: "Game language",
	flight_speed_tt: "How fast the plane moves when flying between airports.",
	music_volume_tt: "Music volume",
	sound_volume_tt: "Sound effects volume",
	// UI
	lost_sauce: "Grandpa's Lost Sauce",
	distance: "Distance",
	flight_cost: "Flight cost",
	fly_to_airport: "Fly to this port",
	new_turn: "Beginning new turn",
	turn: "Turn",
	player: "Player",
	// Options
	options: "Options",
	new_game: "Start a new game",
	start_game: "Start game",
	load_save: "Load / Save game",
	load_game: "Load game",
	save_game: "Save game",
	read_help: "Help",
	read_story: "Story",
	leaderboards: "Leaderboards",
	settings: "Settings",
	close: "Close",
	quest_title: "Grandpa's travels",
	// Menus

	// Dialog
	story_intro_1: "§<c>yellow<c>Ronald§ hasn't seen his grandfather in 20 years and was pretty anxious about the visit.",
	story_intro_2:
		"He remembers his grandfather as a sweet guy, always ready to share \n with him life advice and wisdom, that he learned the hard way in life.",
	story_intro_3: " §<c>yellow<c>Ronald§ knocks at the door, and there was his grandfather, §<c>lime<c>a grin on his face.§",
	story_intro_4: "Hey §<c>yellow<c>Ronald§, long time.",
	story_intro_5: "Hello.",
	story_intro_6: "They sat face to face in his grandfather's personal study.",
	story_intro_7: "You wanted to see me... here I am. How are you?",
	story_intro_8: "Let's skip the pleasantries and all the boring stuff, eh?",
	story_intro_9: "§<c>red<c>I'm about to die.§",
	story_intro_10: "Ok.",
	story_intro_11:
		"So... because you are practically my only family left, I am\nleaving everything I own, and the money I saved for you, but there is a catch...",
	story_intro_12: "I am giving it all to you if you complete a few tasks.",
	story_intro_13: "Which tasks would those be?",
	story_intro_14:
		"I am giving you §<c>gold<c>20000€§ for flight tickets. I need you to §<c>green<c>retrieve 4 items for me from around the world.§",
	story_intro_15: "Accomplish this and you can have everything, which is considerable by the way.",
	story_intro_16:
		"If you don't make it, §<c>crimson<c>I'm liquidating everything I own§, and giving the money to charity, my savings included.",
	story_intro_17: "Well, I guess I need to pack my things then!",
	story_intro_18: "§<c>silver<c>*grandfather grins*§ Brave lad! Here's the 20000€ in cash.",
	story_intro_19: "Good luck!",
	// Languages
	english: "English",
	finnish: "Suomi",
};
