const finnish = {
	code: "finnish",
	name: "Suomi",
	// Stats
	screen_name: "Nimi",
	co2_consumed: "Hiilidioksidi päästöt",
	location: "Paikka",
	money: "Raha",
	time: "päivämäärä",
	real_time: "Peliaika",
	distance_traveled: "Kuljettu matka",
	screen_name_tt: "Tämän hetkisen pelaajan nimi",
	co2_consumed_tt: "Hiilidioksidi päästöt",
	location_tt: "Tämän hetkinen paikka (lentokenttä)",
	money_tt: "Rahasi",
	time_tt: "Tämänhetkinen päivämäärä",
	real_time_tt: "Peliaika",
	distance_traveled_tt: "Yhteensä kuljettu matka",
	// Characters
	narrator: "Kertoja",
	grandfather: "Isoisä",
	ronald: "Ronald",
	// Settings
	gameplay: "Pelattavuus",
	flightSpeed: "Lentonopeus",
	sound: "Ääni",
	musicVolume: "Musiikin äänenvoimakkuus",
	soundVolume: "Efektien äänenvoimakkuus",
	language: "Pelin kieli",
	// Dialog
	story_intro_1: "§<c>yellow<c>Ronald§ ei ole nähnyt isoisäänsä 20 vuoteen ja jännitti odotettua tapaamista.",
	story_intro_2:
		"Hän muistaa isoisänsä mukavana tyyppinä joka on aina valmiina jakamaan elämän viisauksiaan jotka hän oppi kantapään kautta.",
	story_intro_3: "§<c>yellow<c>Ronald§ koputtaa isoisänsä ovelle, jonka takana §<c>lime<c>hän odottaa virne naamallaan.§",
	story_intro_4: "Terve §<c>yellow<c>Ronaldi§, pitkästä aikaa",
	story_intro_5: "Morjes",
	story_intro_6: "He siirtyivät isoisän työhuoneeseen ja istuivat vastakkain.",
	story_intro_7: "Nii, sä halusit nähdä... jote täs mä oon. Miten on menny?",
	story_intro_8: "Ei nyt ruveta käymään mittää tylsiä elämän juttuja läpi.",
	story_intro_9: "§<c>red<c>Kuolema kolkuttaa pian.§",
	story_intro_10: "Vai niin",
	story_intro_11:
		"Jotenkas... sä kun satut olemaan käytännössä mun koko perhe, niin oon päättänyt jättää kaiken mitä omistan sulle... yhellä ehdolla.",
	story_intro_12: "Mä jätän kaiken sulle jos hoidat pari juttua mulle.",
	story_intro_13: "Mitä sä tarviit?",
	story_intro_14: "Heitän sulle §<c>gold<c>20 tonnii§, käytä se raha lentämisee. §<c>green<c>Tartten 4 tavaraa eripuolilt maailmaa.§",
	story_intro_15: "Tässä kun onnistut niin isot rahat ja omaisuudet siirtyy sun nimiin.",
	story_intro_16: "Jos homma ei luista niin §<c>crimson<c>minä pistän kaiken mitä omistan hyväntekeväisyyteen.§",
	story_intro_17: "Kaitpa mun pitää mennä sit pakkaamaan!",
	story_intro_18: "§<c>silver<c>*isoisä virnuilee*§ Nonih, otappa tästä nää rahat!",
	story_intro_19: "Ja onnea matkaan!",
	// Languages
	english: "English",
	finnish: "Suomi",
};
