const finnish = {
	code: "finnish",
	name: "Suomi",
	// Stats
	screen_name: "Nimi",
	co2_consumed: "Hiilidioksidi päästöt",
	location: "Paikka",
	money: "Raha",
	time: "päivämäärä",
	real_time: "Peliaika",
	distance_traveled: "Kuljettu matka",
	screen_name_tt: "Tämän hetkisen pelaajan nimi",
	co2_consumed_tt: "Hiilidioksidi päästöt",
	location_tt: "Tämän hetkinen paikka (lentokenttä)",
	money_tt: "Rahasi",
	time_tt: "Tämänhetkinen päivämäärä",
	real_time_tt: "Peliaika",
	distance_traveled_tt: "Yhteensä kuljettu matka",
	flights_tt: "Lentopisteet",
	score: "Pisteet",
	// Floating texts
	not_enough_flight_points: "§<c>red<c>Liian vähän lentopisteitä!§",
	// Characters
	narrator: "Kertoja",
	grandfather: "Isoisä",
	ronald: "Ronald",
	// Settings
	gameplay: "Pelattavuus",
	flightSpeed: "Lentonopeus",
	sound: "Ääni",
	musicVolume: "Musiikin äänenvoimakkuus",
	soundVolume: "Efektien äänenvoimakkuus",
	game_language: "Pelin kieli",
	// UI
	lost_sauce: "Isoisän Kadonnut Soossi",
	distance: "Matka",
	flight_cost: "Lennon hinta",
	fly_to_airport: "Lennä tälle kentälle",
	// Options
	options: "Valikko",
	new_game: "Aloita uusi peli",
	start_game: "Aloita peli",
	load_save: "Lataa / Tallenna peli",
	load_game: "Lataa peli",
	save_game: "Tallenna peli",
	read_help: "Apua",
	read_story: "Tarina",
	leaderboards: "Pistetaulukko",
	settings: "Asetukset",
	close: "Sulje",
	quest_title: "Isoisän matkailut",
	// Menus
	help_text1: "Grandpa's Lost Sauce is a game where you have to fly around the world, collecting various items your grandpa has forgotten.",
	// Dialog
	story_intro_1: "§<c>yellow<c>Ronald§ ei ole nähnyt isoisäänsä 20 vuoteen ja jännitti odotettua tapaamista.",
	story_intro_2:
		"Hän muistaa isoisänsä mukavana tyyppinä joka on aina valmiina jakamaan elämän viisauksiaan jotka hän oppi kantapään kautta.",
	story_intro_3: "§<c>yellow<c>Ronald§ koputtaa isoisänsä ovelle, jonka takana §<c>lime<c>hän odottaa virne naamallaan.§",
	story_intro_4: "Terve §<c>yellow<c>Ronaldi§, pitkästä aikaa",
	story_intro_5: "Morjes",
	story_intro_6: "He siirtyivät isoisän työhuoneeseen ja istuivat vastakkain.",
	story_intro_7: "Nii, sä halusit nähdä... jote täs mä oon. Miten on menny?",
	story_intro_8: "Ei nyt ruveta käymään mittää tylsiä elämän juttuja läpi.",
	story_intro_9: "§<c>red<c>Kuolema kolkuttaa pian.§",
	story_intro_10: "Vai niin",
	story_intro_11:
		"Jotenkas... sä kun satut olemaan käytännössä mun koko perhe, niin oon päättänyt jättää kaiken mitä omistan sulle... yhellä ehdolla.",
	story_intro_12: "Mä jätän kaiken sulle jos hoidat pari juttua mulle.",
	story_intro_13: "Mitä sä tarviit?",
	story_intro_14: "Heitän sulle §<c>gold<c>20 tonnii§, käytä se raha lentämisee. §<c>green<c>Tartten 4 tavaraa eripuolilt maailmaa.§",
	story_intro_15: "Tässä kun onnistut niin isot rahat ja omaisuudet siirtyy sun nimiin.",
	story_intro_16: "Jos homma ei luista niin §<c>crimson<c>minä pistän kaiken mitä omistan hyväntekeväisyyteen.§",
	story_intro_17: "Kaitpa mun pitää mennä sit pakkaamaan!",
	story_intro_18: "§<c>silver<c>*isoisä virnuilee*§ Nonih, otappa tästä nää rahat!",
	story_intro_19: "Ja onnea matkaan!",
	// Languages
	english: "English",
	finnish: "Suomi",
	// Minigames
	// Adolf's Hangman
	guitar: "kitara",
	guitar_hint: "soitin, jossa on kielet.",
	oxygen: "happi",
	oxygen_hint: "Väritön, hajuton kaasu. Välttämätön elämälle.",
	mountain: "vuori",
	mountain_hint: "Suuri luonnollinen Maapallon pinnan kohoama.",
	painting: "maalaus",
	painting_hint: "Taidemuoto, jossa käytetty värejä tietylle pinnalle, luodakseen kuvan tai ilmaisun.",
	astronomy: "astronomia",
	astronomy_hint: "Taivaankappaleiden ja niiden ilmiöiden tieteellisen tutkimusala.",
	football: "jalkapallo",
	football_hint: "Suosittu urheilulaji, jota pelataan pyöreällä pallolla.",
	chocolate: "suklaa",
	chocolate_hint: "Makea herkku, joka on tehty kaakaopavuista.",
	butterfly: "perhonen",
	butterfly_hint: "Hyönteinen, jolla on värikkäät siivet ja hoikka vartalo.",
	history: "historia",
	history_hint: "Menneiden tapahtumien ja ihmiskunnan tutkimusala.",
	pizza: "pizza",
	pizza_hint: "Herkullinen ruokalaji, joka koostuu pyöreästä alustasta ja täytteistä.",
	jazz: "jazz",
	jazz_hint: "Musiikkigenre, johon mielletään improvisointi ja synkopaatio.",
	camera: "kamera",
	camera_hint: "Laite, jolla otetaan ja tallennetaan kuvia tai videoita",
	diamond: "timantti",
	diamond_hint: "Arvokas jalokivi, joka tunnetaan sen loistosta ja kestävyydestä",
	adventure: "seikkailu",
	adventure_hint: "Jännittävä tai rohkeutta vaativa kokemus.",
	science: "tiede",
	science_hint: "Fyysisen ja luonnollisen maailman järjestelmällinen tutkimus.",
	bicycle: "polkupyörä",
	bicycle_hint: "Ihmisvoimainen kulkuväline, jossa on kaksi pyörää.",
	sunset: "auringonlasku",
	sunset_hint: "Päivittäinen iliö, jossa aurinko laskee horisontin alapuolelle.",
	coffee: "kahvi",
	coffee_hint: "Suosittu kofeiinitäyteinen juoma, joka on tehty paahdetuista kahvipavuista.",
	dance: "tanssi",
	dance_hint: "Rytmitetty kehonliike, joka toteutuu usein musiikin tahdissa.",
	galaxy: "galaksi",
	galaxy_hint: "Valtava painovoiman koossapitämä järjestelmä, joka koostuu tähdistä, pölystä ja kaasusta.",
	orchestra: "orkesteri",
	orchestra_hint: "Iso ryhmä muusikkoja, jotka soittavat useita soittimia.",
	volcano: "tulivuori",
	volcano_hint: "Vuori tai mäki, josta vapautuu laavaa, kiven sirpaleita, kuumaa höyryä sekä kaasua.",
	novel: "novelli",
	novel_hint: "Kookas fiktiivinen teos, joka koostuu monimutkaisista juonista ja hahmoista.",
	sculpture: "veistos",
	sculpture_hint: "Kolmiuloitteinen taideteos. Luotu materiaalia manipuloimalla tai yhdistämällä.",
	symphony: "sinfonia",
	symphony_hint: "Pitkä musiikillinen sävellys kokonaiselle orkesterille, tyypillisesti useissa liikkeissä.",
	architecture: "arkkitehtuuri",
	architecture_hint: "Rakennusten ulkoasun ja toteutuksen suunnittelu.",
	ballet: "baletti",
	ballet_hint: "Klassinen tanssinmuoto, jolle ovat tyypillisiä tarkat ja sirot liikkeet.",
	astronaut: "astronautti",
	astronaut_hint: "Avaruudessa matkustamiseen ja työskentelyyn kouluttettu henkilö.",
	waterfall: "vesiputous",
	waterfall_hint: "Vesiryöppy, joka putoaa joltain korkeudelta.",
	technology: "teknologia",
	technology_hint: "Tieteellisen teorian ja tiedon soveltaminen käytännön tarpeisiin.",
	rainbow: "sateenvarjo",
	rainbow_hint: "Meteorologinen ilmiö, joka syntyy valon heijastumisesta, taittumisesta ja dispersiosta.",
	universe: "universumi",
	universe_hint: "Kaikki olemassaolevan aineen, tilan ja ajan kokonaisuus.",
	piano: "piano",
	piano_hint:
		"Soitin, jota soitetaan painamalla koskettimia, jotka laukaisevat sisäänrakennetut vasarat iskeytymään jännitettyihin metallikieliin.",
	vacation: "loma",
	vacation_hint: "Ajanjakso, joka omistetaan nautinnolle, levolle ja rentoutumiselle.",
	rainforest: "sademetsä",
	rainforest_hint: "Tiheä metsä, jolle on tyypillistä korkea sademäärä ja biologinen monimuotoisuus.",
	theater: "teatteri",
	theater_hint: "Rakennus tai ulkotila, jossa esitetään näytelmiä, elokuvia tai muita esityksiä.",
	telephone: "puhelin",
	telephone_hint: "Laite, jolla lähetetään ääntä pitkien matkojen päähän.",
	language: "kieli",
	language_hint: "Kommunikaatiojärjestelmä, joka muodotuu sanoista, eleistä ja lauseopista.",
	desert: "aavikko",
	desert_hint: "Karu tai kuiva maa, jossa on pieni tai olematon sademäärä.",
	sunflower: "auringonkukka",
	sunflower_hint: "Pitkä kasvi, jolla on iso keltainen kukkapää.",
	fantasy: "fantasia",
	fantasy_hint: "Fiktiivinen genre, jolle ovat tyypillisiä taika ja superluonnolliset elementit.",
	telescope: "teleskooppi",
	telescope_hint: "Optinen laite, jota käytetään avaruuden- ja taivaankappaleiden silmämääräiseen tarkasteluun.",
	breeze: "tuulahdus",
	breeze_hint: "Hellä tuulenvire.",
	oasis: "keidas",
	oasis_hint: "Pieni hedelmällinen alue, josta löytyy vettä.",
	photography: "valokuvaus",
	photography_hint:
		"Taiteenmuoto, prosessi tai harjoitus, jossa luodaan kuvia tallentamalla valon(tai muun lähteen) elektromagneettista säteylyä.",
	safari: "safari",
	safari_hint: "Retkikunta tai matka, tyypillisesti tarkkailemaan villieläinten elämää niille luonnollisessa ympäristössä.",
	planet: "planeetta",
	planet_hint: "Taivaallinen kappale, joka kiertää tähteä tähteä eikä tuota omaa valoa.",
	river: "joki",
	river_hint: "Suuri luonnollinen vesivirta, joka virtaa kanavaa pitkin kohti merta, järveä jne.",
	tropical: "trooppinen",
	tropical_hint: "Liittyy tai sijaitsee Kravun- ja Kauriin kääntöpiirin välissä.",
	mysterious: "mysteerinen",
	mysterious_hint: "Vaikea tai mahdoton ymmärtää, selittää tai tunnistaa.",
	enigma: "arvoitus",
	enigma_hint: "Mysteerinen, hämmentävä tai vaikea ymmärtää.",
	paradox: "paradoksi",
	paradox_hint: "Toteamus tai tilanne, joka on ristiriidassa itsensä kanssa tai uhmaa intuiota.",
	puzzle: "palapeli",
	puzzle_hint: "Peli, lelu tai ongelma, joka on suunniteltu testaamaan nerokkuutta tai tietoa.",
	whisper: "kuiskaus",
	whisper_hint: "Puhua hyvin pehmeästi tai hiljaisesti, usein salailevasti.",
	shadow: "varjo",
	shadow_hint: "Pimeä alue tai muoto, joka syntyy esineen tai hahmon peittäessä valonlähteen.",
	secret: "salaisuus",
	secret_hint: "Jotain, mitä piilotellaan tai pidetään tuntemattomana toisilta.",
	curiosity: "uteliaisuus",
	curiosity_hint: "Vahva halu tietää tai oppia jotain.",
	unpredictable: "arvaamaton",
	unpredictable_hint: "Ei ole ennaltaarvattavissa etukäteen; epävarma.",
	obfuscate: "hämätä",
	obfuscate_hint: "Toisen hämmentäminen; tehdä asiasta vaikeasti ymmärrettävä.",
	unveil: "paljastaa",
	unveil_hint: "Tehdä tiedetyksi tai paljastaa jotain, joka oli ennen salaisuus tai tuntematon.",
	illusion: "illuusio",
	illusion_hint: "Väärä näkemys tai usko; petollinen ulkonäkö tai vaikutelma.",
	moonlight: "kuunvalo",
	moonlight_hint: "Kuusta heijastuva valo.",
	vibrant: "elinvoimainen",
	vibrant_hint: "Täynnä energiaa ja elämäniloa.",
	nostalgia: "nostalgia",
	nostalgia_hint: "Tunteellinen kaipuu tai kiintymys menneisyyteen.",
	brilliant: "nerokas",
	brilliant_hint: "Poikkeuksellisen fiksu, lahjakas tai vaikuttava.",
};
